### ISSUE TITLE
adjust how users change the values

### ISSUE THREAD

**Issue by jxchen01** [MMV-Lab/3D-Cell-Viewer#10]
<img width="445" alt="Screenshot 2024-11-06 at 08 30 29" src="https://github.com/user-attachments/assets/570cc444-30d1-4135-8abf-684cd07c908f">

I think the sliders are much easier to use than simply put a few text field with up/down button. For example, if you look at the "level" on the attached the screenshot, it gives you a very intuitive way to change min/mid/max, but on our version, e.g., "Gamma", it is much harder to adjust.

**Comment by jxchen01** [comment]
If you look at the example from allen cell, the picture in the original issue: for "levels" there are three pins along the slider. This is what we want to change for Gamma. So, for Gamme, it would be good to have only one slider, but with three pins (min, mid, max).

**Comment by Adrian-Sebuliba** [comment]
> @Adrian-Sebuliba If you look at the example from allen cell, the picture in the original issue: for "levels" there are three pins along the slider. This is what we want to change for Gamma. So, for Gamme, it would be good to have only one slider, but with three pins (min, mid, max).

This issue has been addressed

**Comment by jxchen01** [comment]
this is nice! can we do the same fix for clip region? Basically, one slider with two pins for each axis. 3 sliders in total.
<img width="277" alt="Screenshot 2024-11-26 at 08 51 00" src="https://github.com/user-attachments/assets/04ff1ab0-2e3f-47bb-9000-1120930c8a1b">

**Comment by Adrian-Sebuliba** [comment]
> this is nice! can we do the same fix for clip region? Basically, one slider with two pins for each axis. 3 sliders in total. <img alt="Screenshot 2024-11-26 at 08 51 00" width="277" src="https://private-user-images.githubusercontent.com/7811075/389845971-04ff1ab0-2e3f-47bb-9000-1120930c8a1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2Mjc3NTgsIm5iZiI6MTczMjYyNzQ1OCwicGF0aCI6Ii83ODExMDc1LzM4OTg0NTk3MS0wNGZmMWFiMC0yZTNmLTQ3YmItOTAwMC0xMTIwOTMwYzhhMWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjZUMTMyNDE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTY4NTkyNzIxZTRjMzM2OGMyZWFjMzY4NmJmZTJkMjQ2MGIxMDJjNjhmMTMwMWRiMjM0YjZjNDZjODFiNTZiYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.rOhsOvGUX8OfYAQ90hnMy8qk4LRMiU5D3VbUH47PK50">

@jxchen01 The requested changes have been made, thank you!
