### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by haesleinhuepf** [MMV-Lab/3D-Cell-Viewer#12]
Hi all,

the 3D Cell Viewer looks awesome! Great that you are sharing it open source! I was just wondering under which conditions one could reuse the code and tools provided here. Would you mind adding a license file? If you're new to licensing and/or wonder which license to use, you can read more in this blog post: https://focalplane.biologists.com/2023/05/06/if-you-license-it-itll-be-harder-to-steal-it-why-we-should-license-our-work/

Thanks!

Best,
Robert

**Comment by jxchen01** [comment]
fixed in  a4c282e25495bf867c286f299678fc4cfe6a3871
