### ISSUE TITLE
meta data is missing in all files

### ISSUE THREAD

**Issue by jxchen01** [MMV-Lab/3D-Cell-Viewer#19]
Physical Size per Pixel:NaN × NaN × NaN

**Comment by jxchen01** [comment]
no, the fix was wrong ...

**Comment by jxchen01** [comment]
the meta data was wrong.  Currently, you always used 1 micron x 1 micron x 1 micron. This is not correct. Please use the numbers I gave you. If you don't have them, let me know and I can send you again.

**Comment by jxchen01** [comment]
the meta data is still strange .... For example, for this file 220311_muscle6_M4m1p66_z2 ... (I cannot see the full file name under info section, can we fix this issue?)

<img width="311" alt="Screenshot 2024-11-25 at 13 29 13" src="https://github.com/user-attachments/assets/45dd81a3-0acb-4709-9e14-5d4658017c6e">

If you look at info, it shows the file is 300 x 300 x 200, is it XYZ or ZYX?? this is not clear. 

Then, when you display this image in X or Y or Z mode, you will find the number of slices cannot match the info. 

For Z, you can see there are 150 Z-slices under Z-view. But, where does this 150 come from if the image is of size 300 x 300 x 200?

<img width="1083" alt="Screenshot 2024-11-25 at 13 30 35" src="https://github.com/user-attachments/assets/f897b48f-cb4b-48b0-bfd7-9baa3a4b0e88">

**Comment by Adrian-Sebuliba** [comment]
This issue has been addressed

**Comment by jxchen01** [comment]
<img width="259" alt="Screenshot 2024-11-25 at 18 03 58" src="https://github.com/user-attachments/assets/ebd2b96a-c111-4fab-9370-ebda047cd323">
what is the difference between dimension and original dimensions?
