### ISSUE TITLE
isofurface not working

### ISSUE THREAD

**Issue by jxchen01** [MMV-Lab/3D-Cell-Viewer#20]
under channel / enable isosurface / ... then, isovalue and opacity do not work

**Comment by Adrian-Sebuliba** [comment]
That’s strange—I’ve been testing these settings, and they seem to be functioning as expected on my end. Could you please share the file you were working with so I can investigate further?

**Comment by Adrian-Sebuliba** [comment]
> under channel / enable isosurface / ... then, isovalue and opacity do not work

That’s strange—I’ve been testing these settings, and they seem to be functioning as expected on my end. Could you please share the file you were working with so I can investigate further?

**Comment by jxchen01** [comment]
i see. I tried again. I think they are working, just with very small effect.
