### ISSUE TITLE
position of the navigation panel is wrong

### ISSUE THREAD

**Issue by jxchen01** [MMV-Lab/3D-Cell-Viewer#21]
<img width="1197" alt="Screenshot 2024-11-21 at 20 18 36" src="https://github.com/user-attachments/assets/306695ac-7b66-4edd-bf28-16016643f1bc">

the panel blocks the image

**Comment by Adrian-Sebuliba** [comment]
Let me see how I can move it further down to the bottom.

**Comment by jxchen01** [comment]
This may not be the correct solution. It is very common that users want to slide the X value and look at the images simultaneously. It is not good to collapse it. We need to make sure the image is not blocked when users slide the X value.

**Comment by Adrian-Sebuliba** [comment]
> This may not be the correct solution. It is very common that users want to slide the X value and look at the images simultaneously. It is not good to collapse it. We need to make sure the image is not blocked when users slide the X value.

@jxchen01 This issue should now be resolved, I have made a deployment. Please review the changes and let me know if the fix meets your expectations or if there's anything else that needs adjustment. If everything looks good, feel free to close the issue

**Comment by Adrian-Sebuliba** [comment]
@jxchen01 Please remember to clear your browser cache or open the application in a new browser window.

**Comment by Adrian-Sebuliba** [comment]
This issue has been addressed

> <img alt="Screenshot 2024-11-25 at 13 20 51" width="1413" src="https://private-user-images.githubusercontent.com/7811075/389523583-c7e866b3-ec5e-41f6-98a4-4ce8a4f8fcf8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NTQwNjcsIm5iZiI6MTczMjU1Mzc2NywicGF0aCI6Ii83ODExMDc1LzM4OTUyMzU4My1jN2U4NjZiMy1lYzVlLTQxZjYtOThhNC00Y2U4YTRmOGZjZjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjVUMTY1NjA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjY1YmViY2U0M2YxNWE2NWY5ZjA2NmE2MmE0NTk1N2U4MGE1MzI0MjIyMTJlMmNlNjAwYTM0Njc2MGY5ZTIzZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.xMPe7K3M3vywhvUuxvXBYP7AvV3CIrJfun_unR7q8t4"> this is better now.
> Can we add some extra space below this bar? Even though the functionality is fine, the current version does not look nice...

**Comment by Adrian-Sebuliba** [comment]
@jxchen01 Please let me know if you need any further adjustments.
