### ISSUE TITLE
re-order the tabs under "settings"

### ISSUE THREAD

**Issue by jxchen01** [MMV-Lab/3D-Cell-Viewer#23]
currently, by default, when starting the settings, "Render Mode" is unfolded. It is better to keep all tabs folded by default.

Then, let's re-order the tabs: "Channels" --> "Gamma" --> "Exposure" -->  "Camera Mode"--> "View Control" --> "Clip Region" "Camera Settings"  --> "Render Mode" --> "Density" --> "Mask Alpha"

**Comment by Adrian-Sebuliba** [comment]
> currently, by default, when starting the settings, "Render Mode" is unfolded. It is better to keep all tabs folded by default.
> 
> Then, let's re-order the tabs: "Channels" --> "Gamma" --> "Exposure" --> "Camera Mode"--> "View Control" --> "Clip Region" "Camera Settings" --> "Render Mode" --> "Density" --> "Mask Alpha"

Now that we’re reintroducing the rays functionality, where do you suggest we place them in the re-ordering?

**Comment by jxchen01** [comment]
After Density

Jianxu
________________________________

**Comment by Adrian-Sebuliba** [comment]
Issue addressed.
